server:
  port: 7910
  address: localhost

spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.6.253:1521:ORCL
    username: cyp
    password: cyp
    driver-class-name: oracle.jdbc.driver.OracleDriver
    max-idle: 10
    max-wait: 1000
    min-idle : 5
    initial-size : 5
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    view:
      prefix: /
      suffix: .jsp

#  jpa:
#    database: oracle
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      naming:
#        strategy: org.hibernate.cfg.ImprovedNamingStrategy

  redis:
    host: localhost
    password:
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1

  aop:
    auto: true
    proxy-target-class: true

mybatis:
  mapperLocations: classpath:mapping/*.xml
  typeAliasesPackage:  com.ceying.chx.cpi.customer.**.entity

logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder : trace
    org.hibernate.type.descriptor.sql.BasicExtractor : trace
    com.zhang : debug

eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}}
